<?= $this->partial(sprintf("partial/%s/top-navigation", LAYOUT),[
	'a'=>"Admin",'b'=>$this->route,'c'=>$this->controller,'d'=>"Post", "e"=>'editar']); ?>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <!-- Custom Tabs (Pulled to the right) -->
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#tab-1" data-toggle="tab">Geral</a></li>
                        <li><a href="#tab-2" data-toggle="tab">Galeria</a></li>
                        <li class="pull-right header"><i class="fa fa-th"></i> Manutenção dos posts</li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="tab-1">
                            <div id="formContainer">

                            </div>
							<?php $this->ZfForm()->form();?>
                        </div>
                        <!-- /.tab-pane -->
                        <div class="tab-pane" id="tab-2">
                            <div class="row">
                                <div class="col-md-12">
                                    <label for="input-24">Slecione imagens para a galeria!</label>
                                    <div class="file-loading">
                                        <input id="gallery" name="file[]" type="file" multiple>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.tab-pane -->
                    </div>
                    <!-- /.tab-content -->
                </div>
                <!-- nav-tabs-custom -->
            </div>
            <!-- /.col -->
        </div>
    </section>
<?php
$this->inlineScript()->captureStart();
echo $this->partial('partial/gallery-preview',[
	'route'=>$this->route,
	'controller'=>$this->controller,
    'Selector'=>'#gallery'
]);
$this->inlineScript()->captureEnd();
