<!DOCTYPE HTML>
<html>
<head>
	<?= $this->headTitle('Blogname a Blogging Category Flat Bootstarp  Responsive Web Template')->setSeparator(' - ')->setAutoEscape(false) ?>
	<?= $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>
    <!-- Le styles -->
	<?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'web-blog/image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
		->prependStylesheet('http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,300italic,400italic,600italic')
		->prependStylesheet('http://fonts.googleapis.com/css?family=Oswald:100,400,300,700')
		->prependStylesheet($this->basePath('web-blog/css/style.css'))
		->prependStylesheet($this->basePath('web-blog/css/bootstrap.css'))
	?>

    <!-- Scripts -->
	<?= $this->headScript()
		->prependFile($this->basePath('web-blog/js/easing.js'))
		->prependFile($this->basePath('web-blog/js/easing.js'))
		->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js')
	?>
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
        function hideURLbar(){ window.scrollTo(0,1); }
    </script>
	<!----webfonts---->
	<script type="text/javascript">
        jQuery(document).ready(function($) {
            $(".scroll").click(function(event){
                event.preventDefault();
                $('html,body').animate({scrollTop:$(this.hash).offset().top},900);
            });
        });
	</script>
	<!---->

</head>
<body>
<?php
// Within your view
$this->plugin('dateFormat')
	->setTimezone('America/Sao_Paulo')
	->setLocale('pt_BR');  ?>
<div class="banner">
    <div class="header">
        <div class="container">
            <div class="logo">
                <a href="index.html"> <img src="<?=$this->basePath('web-blog/images/logo.png');?>" title="soup" /></a>
            </div>
            <!---start-top-nav---->
            <div class="top-menu">
                <span class="menu"> </span>
                <ul>
                    <li class="active"><a href="<?=$this->url('web')?>">HOME</a></li>
                    <li class="active"><a href="<?=$this->url('web-blog',['action'=>'posts'])?>">POSTS</a></li>
                    <li><a href="<?=$this->url('web-blog',['action'=>'about'])?>">SOBRE</a></li>
                    <li><a href="<?=$this->url('web-blog',['action'=>'contact'])?>">CONTATO</a></li>
                    <div class="clearfix"> </div>
                </ul>
            </div>
            <div class="clearfix"></div>
            <script>
                $("span.menu").click(function(){
                    $(".top-menu ul").slideToggle("slow" , function(){
                    });
                });
            </script>
            <!---//End-top-nav---->
        </div>
    </div>
    <div class="container">
        <div class="banner-head">
            <h1>Lorem ipsum dolor sit amet</h1>
            <h2>cliquam tincidunt mauris</h2>
        </div>
        <div class="banner-links">
            <ul>
                <li class="active"><a href="#">LOREM IPSUM</a></li>
                <li><a href="#">DOLAR SITE AMET</a></li>
                <li><a href="#">MORBI IN SEM</a></li>
                <div class="clearfix"></div>
            </ul>
        </div>
    </div>
</div>
<!---//End-banner---->
<?= $this->content ?>
<div class="fotter">
	<div class="container">
		<div class="col-md-4 fotter-info">
			<h3>INTEGER VITAE LIBERO</h3>
			<p>Raesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. </p>
			<p>Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus. Phasellus ultrices nulla quis nibh. Quisque a lectus. </p>
		</div>
		<div class="col-md-4 fotter-list">
			<h3>VESTIBULUM COMMO</h3>
			<ul>
				<li><a href="#">Ut alliquam solicitudin</a></li>
				<li><a href="#">Neque id cursus faucibus</a></li>
				<li><a href="#">Raesent dapibus neque id cursus</a></li>
			</ul>
		</div>
		<div class="col-md-4 fotter-media">
			<h3>FOLLOW US ON....</h3>
			<div class="social-icons">
				<a href="https://www.facebook.com/claudio.coelho.775"><span class="fb"> </span></a>
				<a href="https://twitter.com/callcocam"><span class="twt"> </span></a>
				<a href="#"><span class="in"> </span></a>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
</div>
<!---fotter/-->
<div class="copywrite">
	<div class="container">
		<p>Copyrights &copy; 2015 Blogging All rights reserved | Template by <a href="http://w3layouts.com/">W3layouts</a></p>
	</div>
</div>
<!---->
<script type="text/javascript">
    $(document).ready(function() {
		/*
		 var defaults = {
		 containerID: 'toTop', // fading element id
		 containerHoverID: 'toTopHover', // fading element hover id
		 scrollSpeed: 1200,
		 easingType: 'linear'
		 };
		 */
        $().UItoTop({ easingType: 'easeOutQuart' });
    });
</script>
<a href="#to-top" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>


</body>
</html>