<div class="content">
    <div class="row">
		<?php
        $i=1;
        foreach($this->rows as $row):
			?>
            <div class="col-md-4">
                <!-- Widget: user widget style 1 -->
                <div class="box box-widget widget-user-2">
                    <!-- Add the bg color to the header using any of the bg-* classes -->
                    <div class="widget-user-header bg-yellow">
                        <div class="widget-user-image">
                            <?=$row['cover'];?>
                        </div>
                        <!-- /.widget-user-image -->
                        <h3 class="widget-user-username"><?=$row['title']?></h3>
                        <h5 class="widget-user-desc"><?=$row['uf']?></h5>
                    </div>
                    <div class="box-footer no-padding">
                        <ul class="nav nav-stacked">
                            <li><a href="#">Cep <span class="pull-right badge bg-blue"><?=$row['cep']?></span></a></li>
                            <li><a href="#">Ibge <span class="pull-right badge bg-aqua"><?=$row['ibge']?></span></a></li>
                            <li><a href="#">Pais <span class="pull-right badge bg-green"><?=$row['xpais']?></span></a></li>
                            <li><a href="#">Status <span class="pull-right badge bg-red"><?=$row['status']?></span></a></li>
                        </ul>
                    </div>
                </div>
                <!-- /.widget-user -->
            </div>
		<?php
        if($i>=3):?>
    </div>
    <div class="row">
        <?php
        $i=0;
        endif;
        $i++;
        endforeach;?>
    </div>
</div>