<?php $users = $this->identity();?><div class="lockscreen-wrapper">
	<div class="lockscreen-logo">
		<a href="<?=$this->url('admin');?>"><b>Permissão</b> negada</a>
	</div>
	<!-- User name -->

	<!-- START LOCK SCREEN ITEM -->
	<div class="lockscreen-item">
		<!-- lockscreen image -->
		<div class="lockscreen-image">
			<img src="<?=$users->cover;?>" alt="User Image">
		</div>
		<!-- /.lockscreen-image -->

		<!-- lockscreen credentials (contains the form) -->
		<div class="lockscreen-credentials">
			<div class="input-group">
				<input type="text" class="form-control" placeholder="User" value="<?=$users->first_name;?> <?=$users->last_name;?>">

				<div class="input-group-btn">
					<a href="<?=$this->url('admin');?>" class="btn"><i class="fa fa-arrow-right text-muted"></i></a>
				</div>
			</div>
		</div>
		<!-- /.lockscreen credentials -->

	</div>
	<!-- /.lockscreen-item -->
	<div class="help-block text-center">
		Voce não pode acessar essa pagina!
	</div>
	<div class="text-center">
		<a class="btn btn-danger" href="<?=$this->url('auth/default', [
			'controller'=>'auth',
			'action'=>'sair'
		]);?>">Sair do sistema</a>
	</div>
</div>