<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<?= $this->headTitle('AdminLTE 2 | LTE')->setSeparator(' - ')->setAutoEscape(false) ?>

	<?= $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge');?>

	<!-- Le styles -->
	<?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
		->prependStylesheet('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic')
		->prependStylesheet($this->basePath('css/style.css'))
		->prependStylesheet($this->basePath('css/zf-table.css'))
		->prependStylesheet($this->basePath('assets/toastr.min.css'))
		->prependStylesheet($this->basePath('assets/jquery-confirm.min.css'))
		->prependStylesheet($this->basePath('assets/css/fileinput.css'))
		->prependStylesheet($this->basePath('assets/themes/explorer-fa/theme.css'))
		->prependStylesheet($this->basePath('lte-admin/css/skins/skin-blue.min.css'))
		->prependStylesheet($this->basePath('lte-admin/css/AdminLTE.min.css'))
		->prependStylesheet($this->basePath('lte-admin/plugins/iCheck/square/_all.css'))
		->prependStylesheet($this->basePath('lte-admin/Ionicons/css/ionicons.min.css'))
		->prependStylesheet($this->basePath('lte-admin/font-awesome/css/font-awesome.min.css'))
		->prependStylesheet($this->basePath('lte-admin/bootstrap/dist/css/bootstrap.min.css'))?>
    <!-- REQUIRED JS SCRIPTS -->
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
	<!-- Main Header -->
	<header class="main-header">
		<!-- Logo -->
		<a href="index2.html" class="logo">
			<!-- mini logo for sidebar mini 50x50 pixels -->
			<span class="logo-mini"><b>A</b>LT</span>
			<!-- logo for regular state and mobile devices -->
			<span class="logo-lg"><b>Admin</b>LTE</span>
		</a>
		<!-- Header Navbar -->
		<?=$this->partial('partial/admin-lte/operacional/main-header');?>
	</header>
	<!-- Left side column. contains the logo and sidebar -->
	<aside class="main-sidebar">
		<!-- sidebar: style can be found in sidebar.less -->
		<?=$this->navigation('Navigation')->menu()->setPartial('partial/admin-lte/operacional/sidebar'); ?>
			<!-- /.sidebar -->
	</aside>
	<!-- Content Wrapper. Contains page content -->
	<div class="content-wrapper">
		<!-- Content Header (Page header) -->
		<!-- Main content -->
		<section class="content container-fluid">
			  <?= $this->content ?>
			<!--------------------------
			  | Your Page Content Here |
			  -------------------------->

		</section>
		<!-- /.content -->
	</div>
	<!-- /.content-wrapper -->

	<!-- Main Footer -->
	<footer class="main-footer">
		<!-- To the right -->
		<div class="pull-right hidden-xs">
			Anything you want
		</div>
		<!-- Default to the left -->
		<strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.
	</footer>

	<!-- Control Sidebar -->
	<aside class="control-sidebar control-sidebar-dark">
		<!-- Create the tabs -->
		<ul class="nav nav-tabs nav-justified control-sidebar-tabs">
			<li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
			<li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
		</ul>
		<!-- Tab panes -->
		<div class="tab-content">
			<!-- Home tab content -->
			<div class="tab-pane active" id="control-sidebar-home-tab">
				<h3 class="control-sidebar-heading">Recent Activity</h3>
				<ul class="control-sidebar-menu">
					<li>
						<a href="javascript:;">
							<i class="menu-icon fa fa-birthday-cake bg-red"></i>

							<div class="menu-info">
								<h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

								<p>Will be 23 on April 24th</p>
							</div>
						</a>
					</li>
				</ul>
				<!-- /.control-sidebar-menu -->

				<h3 class="control-sidebar-heading">Tasks Progress</h3>
				<ul class="control-sidebar-menu">
					<li>
						<a href="javascript:;">
							<h4 class="control-sidebar-subheading">
								Custom Template Design
								<span class="pull-right-container">
                    <span class="label label-danger pull-right">70%</span>
                  </span>
							</h4>

							<div class="progress progress-xxs">
								<div class="progress-bar progress-bar-danger" style="width: 70%"></div>
							</div>
						</a>
					</li>
				</ul>
				<!-- /.control-sidebar-menu -->

			</div>
			<!-- /.tab-pane -->
			<!-- Stats tab content -->
			<div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
			<!-- /.tab-pane -->
			<!-- Settings tab content -->
			<div class="tab-pane" id="control-sidebar-settings-tab">
				<form method="post">
					<h3 class="control-sidebar-heading">General Settings</h3>

					<div class="form-group">
						<label class="control-sidebar-subheading">
							Report panel usage
							<input type="checkbox" class="pull-right" checked>
						</label>

						<p>
							Some information about this general settings option
						</p>
					</div>
					<!-- /.form-group -->
				</form>
			</div>
			<!-- /.tab-pane -->
		</div>
	</aside>
	<!-- /.control-sidebar -->
	<!-- Add the sidebar's background. This div must be placed
	immediately after the control sidebar -->
	<div class="control-sidebar-bg"></div>
</div>
<div class="body-processing">
    <div class="processing">
        <p style="margin-top: 15px"></p>
    </div>
</div>
<!-- ./wrapper -->
<!-- REQUIRED JS SCRIPTS -->
<?= $this->inlineScript()
		->appendFile(
		'https://oss.maxcdn.com/respond/1.4.2/respond.min.js',
		'text/javascript',
		['conditional' => 'lt IE 9']
	)->appendFile(
		'https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js',
		'text/javascript',
		['conditional' => 'lt IE 9']
	)->prependFile($this->basePath('js/app.js'))
	->prependFile($this->basePath('js/zf-table.js'))
	->prependFile($this->basePath('lte-admin/js/adminlte.js'))
	->prependFile($this->basePath('assets/toastr.min.js'))
	->prependFile($this->basePath('assets/jquery-confirm.min.js'))
	->prependFile($this->basePath('assets/js/locales/pt-BR.js'))
	->prependFile($this->basePath('assets/themes/explorer-fa/theme.js'))
	->prependFile($this->basePath('assets/js/fileinput.js'))
	->prependFile($this->basePath('js/jquery.form.min.js'))
	->prependFile($this->basePath('lte-admin/plugins/iCheck/icheck.min.js'))
	->prependFile($this->basePath('lte-admin/bootstrap/dist/js/bootstrap.min.js'))
    ->prependFile($this->basePath('lte-admin/jquery/dist/jquery.min.js'))
?>
<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->
</body>
</html>