<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<?= $this->headTitle('AdminLTE 2 | LTE-Login')->setSeparator(' - ')->setAutoEscape(false) ?>

	<?= $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<!-- Le styles -->
	<?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])

		->prependStylesheet('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic')
		->prependStylesheet($this->basePath('css/style.css'))
		->prependStylesheet($this->basePath('lte-admin/css/skins/skin-blue.min.css'))
        ->prependStylesheet($this->basePath('assets/toastr.min.css'))
		->prependStylesheet($this->basePath('lte-admin/plugins/iCheck/square/blue.css'))
		->prependStylesheet($this->basePath('lte-admin/css/AdminLTE.min.css'))
		->prependStylesheet($this->basePath('lte-admin/Ionicons/css/ionicons.min.css'))
		->prependStylesheet($this->basePath('lte-admin/font-awesome/css/font-awesome.min.css'))
		->prependStylesheet($this->basePath('lte-admin/bootstrap/dist/css/bootstrap.min.css'))
	?>
	<?= $this->headScript()
		->appendFile(
			'https://oss.maxcdn.com/respond/1.4.2/respond.min.js',
			'text/javascript',
			['conditional' => 'lt IE 9']
		)->appendFile(
			'https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js',
			'text/javascript',
			['conditional' => 'lt IE 9']
		)->prependFile($this->basePath('lte-admin/jquery/dist/jquery.min.js'))
	?>
</head>
<body class="hold-transition login-page">
    <!-- Content Wrapper. Contains page content -->
    <?= $this->content ?>
    <!-- ./wrapper -->
    <div class="body-processing">
        <div class="processing">
        </div>
    </div>
	 <!-- ./wrapper -->
    <!-- REQUIRED JS SCRIPTS -->
	<?= $this->inlineScript()
		->prependFile($this->basePath('js/app.js'))
		->prependFile($this->basePath('lte-admin/js/adminlte.js'))
		->prependFile($this->basePath('assets/toastr.min.js'))
		->prependFile($this->basePath('js/jquery.form.min.js'))
		->prependFile($this->basePath('lte-admin/bootstrap/dist/js/bootstrap.min.js'))
	?>

    <!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->
</body>
</html>