<?php $users = $this->identity();?>
<nav class="navbar navbar-static-top" role="navigation">
	<!-- Sidebar toggle button-->
	<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
		<span class="sr-only">Toggle navigation</span>
	</a>
	<!-- Navbar Right Menu -->
	<div class="navbar-custom-menu">
		<ul class="nav navbar-nav">
			<!-- Messages: style can be found in dropdown.less-->
			<!-- User Account Menu -->
			<li class="dropdown user user-menu">
				<!-- Menu Toggle Button -->
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					<!-- The user image in the navbar-->
					<img src="<?=$this->basePath($users->cover)?>" class="user-image" alt="<?=$users->first_name?>">
					<!-- hidden-xs hides the username on small devices so only the image appears. -->
					<span class="hidden-xs">Alexander Pierce</span>
				</a>
				<ul class="dropdown-menu">
					<!-- The user image in the menu -->
					<li class="user-header">
						<img src="<?=$this->basePath($users->cover)?>" class="img-circle" alt="<?=$users->first_name?>">

						<p>
							<?=$users->first_name?> <?=$users->last_name?> - Web Developer
							<small>Membro Desde <?=date("M, Y", strtotime($users->created_at))?> </small>
						</p>
					</li>
					<!-- Menu Body -->
					<li class="user-body">
						<div class="row">

						</div>
						<!-- /.row -->
					</li>
					<!-- Menu Footer-->
					<li class="user-footer">
						<div class="pull-left">
							<a href="<?=$this->url('admin');?>" class="btn btn-default btn-flat">Minha Conta</a>
						</div>
						<div class="pull-right">
							<a href="<?=$this->url('auth/default', [
								'controller'=>'auth',
								'action'=>'sair'
							]);?>" class="btn btn-default btn-flat">Sair Do Sistema</a>
						</div>
					</li>
				</ul>
			</li>
			<!-- Control Sidebar Toggle Button -->
			<li>
				<a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
			</li>
		</ul>
	</div>
</nav>