<section class="sidebar">
	<?php $users = $this->identity();?>
	<!-- Sidebar user panel (optional) -->
	<div class="user-panel">
		<div class="pull-left image">
			<img src="<?=$this->basePath($users->cover)?>" class="img-circle" alt="<?=$users->first_name?>">
		</div>
		<div class="pull-left info">
			<p><?=$users->first_name?> <?=$users->last_name?></p>
			<!-- Status -->
			<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
		</div>
	</div>

	<!-- search form (Optional) -->
	<form action="#" method="get" class="sidebar-form">
		<div class="input-group">
			<input type="text" name="q" class="form-control" placeholder="Search...">
			<span class="input-group-btn">
              <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
              </button>
            </span>
		</div>
	</form>
	<!-- /.search form -->

	<!-- Sidebar Menu -->
	<ul class="sidebar-menu" data-widget="tree">
		<li class="header">HEADER</li>
		<!-- Optionally, you can add icons to the links -->
		<li class="active"><a href="<?=$this->url('admin');?>"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
		<li><a href="#"><i class="fa fa-link"></i> <span>Another Link</span></a></li>
		<li class="treeview">
			<a href="#"><i class="fa fa-link"></i> <span>Multilevel</span>
				<span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
			</a>
			<ul class="treeview-menu">
				<li><a href="#">Link in level 2</a></li>
				<li><a href="#">Link in level 2</a></li>
			</ul>
		</li>
        <li class="divider"></li>
        <li><a href="<?=$this->url('auth/default', [
				'controller'=>'auth',
				'action'=>'sair'
			]);?>"><i class="fa fa-sign-out"></i> <span>Sair Do Sistema</span></a></li>
    </ul>
	<!-- /.sidebar-menu -->
</section>