<section class="sidebar">
	<?php $users = $this->identity();?>
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
        <div class="pull-left image">
            <img src="<?=$this->basePath($users->cover)?>" class="img-circle" alt="<?=$users->first_name?>">
        </div>
        <div class="pull-left info">
            <p><?=$users->first_name?> <?=$users->last_name?></p>
            <!-- Status -->
            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
    </div>

    <!-- search form (Optional) -->
    <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
            <input type="text" name="q" class="form-control" placeholder="Search...">
            <span class="input-group-btn">
              <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
              </button>
            </span>
        </div>
    </form>
    <!-- /.search form -->
    <!-- Sidebar Menu -->
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">HEADER</li>
		<!-- Optionally, you can add icons to the links -->
        <li><a href="<?=$this->url('admin');?>"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>

		<?php
		/* @var $container Zend\Navigation\Navigation */
		$container = $this->container;
		if ($container):?>
			<?php foreach ($container as $page): ?>
			<?php if (!$this->navigation()->accept($page)) continue; ?>
			<?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
			<?php $hasChildren = $page->hasPages() ?>
			<?php
			if ($hasChildren):
				//check if access is allowed at least one item
				$access = false;
				foreach ($page->getPages() as $child) {
					if ($this->navigation()->accept($child) && $child->get("separator") !== true) {
						$access = true;
					}
				}
				if ($access) :
					?>
                    <li class="treeview <?php if ($page->isActive(true)) echo ' active' ?>">
                        <a href="#">
							<?php if ($page->get("icone") !== ""): ?>
                                <i class="<?=$page->get("icone"); ?>"></i>
							<?php endif; ?>
                            <span>
                                <?=$this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?></span>

                        </a>
                        <ul class="treeview-menu">
							<?php foreach ($page->getPages() as $child): ?>
								<?php if (!$this->navigation()->accept($child)) continue; ?>
								<?php if ($child->get("separator") === true): ?>
                                    <li class="divider"></li>
									<?php
									continue;
								endif;
								?>
                                <li class="<?=$child->isActive()? 'active':'' ?>">
                                    <a href="<?=$child->getHref();?>"
										<?php if ($child->getTarget() != ""): ?>
                                            target="<?=$child->getTarget(); ?>"
										<?php endif; ?> >
										<?php if ($child->get("icone") !== ""): ?>
                                            <i class="<?=$child->get("icone"); ?>"></i>
										<?php endif; ?>
                                        <span><?=$this->escapeHtml($this->translate($child->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?></span>
                                    </a>
                                </li>
							<?php endforeach ?>
                        </ul>
                    </li>
				<?php endif; ?>
			<?php else: ?>
                <li class="<?=$page->isActive()?' active':'' ?>">
                    <a href="<?=$page->getHref()?>"
						<?php if ($page->getTarget() != ""): ?>
                            target="<?php echo $page->getTarget(); ?>"
						<?php endif; ?> >
						<?php if ($page->get("icone") !== ""): ?>
                            <i class="<?=$page->get("icone"); ?>"></i>
						<?php endif; ?>
                        <span><?=$this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?></span>
                    </a>
                </li>

			<?php endif ?>
		<?php endforeach ?>

			<?php
		endif;
		?>
        <li class="divider"></li>
        <li><a href="<?=$this->url('auth/default', [
				'controller'=>'auth',
				'action'=>'sair'
			]);?>"><i class="fa fa-sign-out"></i> <span>Sair Do Sistema</span></a></li>
    </ul>
    <!-- /.sidebar-menu -->
</section>