<form method="post" enctype="multipart/form-data" class="modal fade modal-xs in" id="modal-default" action="<?=$this->url($this->route, [
	'controller'=>$this->controller,
	'action'=>'upload',
	'id'=>$this->Route()->getId()
])?>" name="AjaxUploadForm">
    <div class="modal-dialog  modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span></button>
                <h4 class="modal-title">Upload Imagem</h4>
            </div>
            <div class="modal-body">
                <div class="box box-primary">
                    <div class="box-body box-profile">
                        <img id="file" data-cover="<?=$this->file?>" style="width: 100%" class="attachment profile-user-img img-responsive" src="<?=$this->url($this->route, ['controller'=>$this->controller,'action'=>'file'],
							['query'=>['name'=>$this->file, 'thumbnail'=>true]]);?>" alt="User profile picture">
                        <div class="form-group">
                            <div class="btn btn-default btn-warning btn-file btn-block">
                                <i class="fa fa-paperclip"></i> Selecione uma imagem
                                <input name="file"  type="file">
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
            <div class="modal-footer">
                <div class="row">
                    <!-- /.col -->
                    <div class="col-xs-6">
                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fechar</button>
                    </div>
                    <div class="col-xs-6">
                        <input name="submit" id="button" class="btn btn-primary  pull-right" value="Enviar Imagem" type="submit">
                    </div>
                    <!-- /.col -->
                </div>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
</form>

