<?=$this->partial('partial/form-error',['form'=>$this->form]);?>
<?=$this->form()->openTag($this->form->setAttribute('action',$this->url($this->route, [
	'controller'=>$this->controller,
	'action'=>'editar-form'
]))->setAttribute('name','AjaxForm')->setAttribute('class',''));?>
<?php
$formLayouty='group';
//$formLayouty='inline';
?>
<div class="row">
    <div class="col-md-8 col-xs-12">

		<?=$this->formHidden($this->form->get('id'));?>
		<?=$this->formHidden($this->form->get('tipo'));?>

		<?=$this->partial(sprintf('partial/%s/form/input-%s', LAYOUT,$formLayouty),[
			'field'=>$this->form->get('social')
		]);?>

		<?=$this->partial(sprintf('partial/%s/form/input-%s', LAYOUT,$formLayouty),[
			'field'=>$this->form->get('fantasia')
		]);?>
        <div class="col-sm-9">
            <h4>Documentos da empresa:</h4>
        </div>
		<?=$this->partial(sprintf('partial/%s/form/input-%s', LAYOUT,$formLayouty),[
			'field'=>$this->form->get('cnpj')
		]);?>
		<?=$this->partial(sprintf('partial/%s/form/input-%s', LAYOUT,$formLayouty),[
			'field'=>$this->form->get('ie')
		]);?>
        <div class="col-sm-9">
            <h4>Contato da empresa:</h4>
        </div>

		<?=$this->partial(sprintf('partial/%s/form/input-%s', LAYOUT,$formLayouty),[
			'field'=>$this->form->get('phone')
		]);?>

		<?=$this->partial(sprintf('partial/%s/form/input-%s', LAYOUT,$formLayouty),[
			'field'=>$this->form->get('email')
		]);?>

        <div class="col-sm-9">
            <h4>Endereço da empresa:</h4>
        </div>

		<?=$this->partial(sprintf('partial/%s/form/input-%s', LAYOUT,$formLayouty),[
			'field'=>$this->form->get('street')
		]);?>
		<?=$this->partial(sprintf('partial/%s/form/input-%s', LAYOUT,$formLayouty),[
			'field'=>$this->form->get('zip')
		]);?>

		<?=$this->partial(sprintf('partial/%s/form/input-%s', LAYOUT,$formLayouty),[
			'field'=>$this->form->get('district')
		]);?>

		<?=$this->partial(sprintf('partial/%s/form/input-%s', LAYOUT,$formLayouty),[
			'field'=>$this->form->get('number')
		]);?>

		<?=$this->partial(sprintf('partial/%s/form/input-%s', LAYOUT,$formLayouty),[
			'field'=>$this->form->get('complements')
		]);?>

		<?=$this->partial(sprintf('partial/%s/form/input-%s', LAYOUT,$formLayouty),[
			'field'=>$this->form->get('city')
		]);?>

		<?=$this->partial(sprintf('partial/%s/form/input-%s', LAYOUT,$formLayouty),[
			'field'=>$this->form->get('state')
		]);?>

		<?=$this->partial(sprintf('partial/%s/form/input-%s', LAYOUT,$formLayouty),[
			'field'=>$this->form->get('country')
		]);?>
    </div>
    <div class="col-md-4 col-xs-12">
		<?=$this->partial(sprintf('partial/%s/form/input-file', LAYOUT,$formLayouty),[
			'field'=>$this->form->get('cover'),
			'route'=>$this->route,
			'controller'=>$this->controller,
			'id'=>$this->form->get('id')->getValue(),
			'action'=>'upload-modal',
		]);?>
        <div class="col-sm-9">
            <h4>Cadastro da empresa:</h4>
        </div>
		<?=$this->partial(sprintf('partial/%s/form/input-%s', LAYOUT,$formLayouty),[
			'field'=>$this->form->get('created_at')
		]);?>

		<?=$this->partial(sprintf('partial/%s/form/input-%s', LAYOUT,$formLayouty),[
			'field'=>$this->form->get('updated_at')
		]);?>

    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <!-- /.col -->
    <div class="col-xs-6">
		<?=$this->formSubmit($this->form->get('submit')->setValue('Atualizar Empresa'));?>
    </div>
    <div class="col-xs-6">
        <a href="<?=$this->url($this->route, [
			'controller'=>$this->controller
		])?>" class="btn btn-warning btn-block"><i class="fa fa-backward"></i> Voltar Para a Lista </a>
    </div>
    <!-- /.col -->
</div>
<?=$this->form()->closeTag();?>
<?=$this->partial('partial/messages');?>
