<div class="login-box">
	<div class="login-logo">
		<a href="<?=$this->url('home')?>"><b>Admin</b>LTE</a>
	</div>
	<!-- /.login-logo -->
	<div class="login-box-body">
		<p class="login-box-msg">Faça o Login Para Iniciar A Sessão</p>

		<?=$this->form()->openTag($this->form);?>
			<div class="form-group has-feedback">
				<?=$this->formRow($this->form->get('email'));?>
				<span class="glyphicon glyphicon-envelope form-control-feedback"></span>
			</div>
			<div class="form-group has-feedback">
				<?=$this->formRow($this->form->get('password'));?>
				<span class="glyphicon glyphicon-lock form-control-feedback"></span>
			</div>
			<div class="row">
				<div class="col-xs-12">
					<?=$this->formSubmit($this->form->get('submit')->setValue("Iniciar Sessão"));?>
				</div>
				<!-- /.col -->
			</div>
		<?=$this->form()->closeTag();?>

		<div class="social-auth-links text-center">
			<p>- OR -</p>
		</div>
		<!-- /.social-auth-links -->

		<a href="<?=$this->url('auth/forgout')?>">Esqueci minha senha</a><br>
		<a href="<?=$this->url('auth/register')?>" class="text-center">Não sou cadastrado</a>

	</div>
	<!-- /.login-box-body -->
</div>