<?=$this->partial('partial/admin-lte/form-error',['form'=>$this->form]);?>

<?=$this->form()->openTag($this->form->setAttribute('action',$this->url('auth/recuperar-senha/recuperar-senha-form')));?>

<?=$this->partial('partial/admin-lte/form/input-form-group',[
	'field'=>$this->form->get('email')->setLabel("")
]);?>
  <div class="row">
        <!-- /.col -->
        <div class="col-xs-12">
			<?=$this->formSubmit($this->form->get('submit')->setValue('Solicitar Nova Senha'));?>
        </div>
        <!-- /.col -->
    </div>
<?=$this->form()->closeTag();?>