<div class="register-box">
	<div class="register-logo">
		<a href="<?=$this->url('home')?>"><b>Admin</b>LTE</a>
	</div>

	<div class="register-box-body">
		<p class="login-box-msg">Recuperar minha senha</p>

		<?=$this->form()->openTag($this->form);?>
        <div class="form-group has-feedback">
			<?=$this->formRow($this->form->get('email'));?>
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        </div>
         <div class="row">
            <div class="col-xs-12">
				<?=$this->formSubmit($this->form->get('submit')->setValue("Recuperar Senha"));?>
            </div>
            <!-- /.col -->
        </div>
		<?=$this->form()->closeTag();?>

        <div class="social-auth-links text-center">
            <p>- OR -</p>
        </div>
		<a href="<?=$this->url('auth')?>" class="text-center">Voltar para o login</a>
	</div>
	<!-- /.form-box -->
</div>