<?php
$this->formElementErrors()
	->setMessageOpenFormat('<div class="help-inline red">')
	->setMessageSeparatorString('</div><div class="help-inline">')
	->setMessageCloseString('</div>')
	->render($this->form);
?>
<?=$this->form()->openTag($this->form->setAttribute('action',$this->url('auth/register/form')));?>
    <div class="form-group has-feedback">
		<?=$this->formRow($this->form->get('first_name')->setLabel(""));?>
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
    </div>
    <div class="form-group has-feedback">
		<?=$this->formRow($this->form->get('last_name')->setLabel(""));?>
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
    </div>

    <div class="form-group has-feedback">
		<?=$this->formRow($this->form->get('email')->setLabel(""));?>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
    </div>
    <div class="form-group has-feedback">
		<?=$this->formRow($this->form->get('password')->setLabel(""));?>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
    </div>
    <div class="row">
        <!-- /.col -->
        <div class="col-xs-12">
            <?=$this->formSubmit($this->form->get('submit')->setValue('Criar Conta'));?>
         </div>
        <!-- /.col -->
    </div>
	<?=$this->form()->closeTag();?>
