<div class="register-box">
	<div class="register-logo">
	<a href="<?=$this->url('home')?>"><b>Admin</b>LTE</a>
</div>

<div class="register-box-body">
	<p class="login-box-msg">Formulario de cadastro</p>
	<?=$this->form()->openTag($this->form->setAttribute('action',$this->url('auth/register')));?>
    <div class="form-group has-feedback">
		<?=$this->formRow($this->form->get('first_name')->setLabel(""));?>
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
    </div>
    <div class="form-group has-feedback">
		<?=$this->formRow($this->form->get('last_name')->setLabel(""));?>
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
    </div>

    <div class="form-group has-feedback">
		<?=$this->formRow($this->form->get('email')->setLabel(""));?>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
    </div>
    <div class="form-group has-feedback">
		<?=$this->formRow($this->form->get('password')->setLabel(""));?>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
    </div>
    <div class="row">
        <!-- /.col -->
        <div class="col-xs-12">
            <?=$this->formSubmit($this->form->get('submit')->setValue('Criar Conta'));?>
         </div>
        <!-- /.col -->
    </div>
	<?=$this->form()->closeTag();?>

	<div class="social-auth-links text-center">
		<p>- OR -</p>
	</div>

	<a href="<?=$this->url('auth')?>" class="text-center">Ja sou cadastrado</a>
</div>
<!-- /.form-box -->
</div>