<?php
$form = $this->form;
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();
?>

<h1>Upload a New Image</h1>

<p>
    Please fill out the following form and press the <i>Upload</i> button.
</p>

<div class="row">
    <div class="col-md-6">
		<?= $this->form()->openTag($form->setAttribute('action',$this->url("upload"))); ?>

        <div class="form-group">
			<?= $this->formLabel($form->get('file')); ?>
			<?= $this->formElement($form->get('file')); ?>
			<?= $this->formElementErrors($form->get('file')); ?>
            <div class="hint">(PNG and JPG formats are allowed)</div>
        </div>

		<?= $this->formElement($form->get('submit')); ?>

		<?= $this->form()->closeTag(); ?>
    </div>
</div>

<hr/>

<?php if(count($files)==0): ?>

    <p>
        <i>There are no files to display.</i>
    </p>

<?php else: ?>

    <div class="row">
        <div class="col-sm-6 col-md-12">

			<?php foreach($files as $file): ?>

                <div class="img-thumbnail">

                    <img title="<?php echo $file; ?>" src="<?= $this->url('images', ['action'=>'file'],
						['query'=>['name'=>$file, 'thumbnail'=>true]]); ?>">

                    <div class="caption">
                         <p>
                            <a title="<?php echo $file; ?>" target="_blank" href="<?= $this->url('images', ['controller'=>'admin','action'=>'file'],
								['query'=>['name'=>$file]]); ?>"
                               class="btn btn-default" role="button">Show in Natural Size</a>
                        </p>
                    </div>
                </div>

			<?php endforeach; ?>
        </div>
    </div>

<?php endif; ?>

<hr/>
