<?php
/**
 * Created by PhpStorm.
 * User: caltj
 * Date: 26/12/2017
 * Time: 14:37
 */

namespace Core\View\Helper;


use Admin\Table\MenuTable;
use Auth\Adapter\Authentication;
use Core\Factory\AclFactory;
use Interop\Container\ContainerInterface;
use Zend\Permissions\Acl;
use Zend\View\Helper\AbstractHelper;
use Zend\View\Helper\Navigation;

class NavigationHelper extends Navigation
{


	const DEFAULT_ROLE = 'admin';
	/**
	 * @var ContainerInterface
	 */
	private $container;

	/**
	 * NavigationHelper constructor.
	 *
	 * @param ContainerInterface $container
	 */
	public function __construct(ContainerInterface $container)
	{
		$this->container = $container;
	}
	/**
	 * Sets ACL to use when iterating pages
	 *
	 * Implements {@link HelperInterface::setAcl()}.
	 *
	 * @param  Acl\AclInterface $acl ACL object.
	 *
	 * @return AbstractHelper
	 */
	public function setAcl(Acl\AclInterface $acl = null)
	{
		$acl = $this->container->get(AclFactory::class);
		return parent::setAcl($acl); // TODO: Change the autogenerated stub
	}
}