<div class="zf-table-wrap  form-inline">
    <div class="table-header">
    </div>
    <div class="row ">
        <div class="col-sm-6 pull-left">
            <?php if($this->name): ?>
                <header>
                    <h4><?= $this->name ?></h4>
                </header>
            <?php endif;?>
        </div>
        <?php if ($this->showQuickSearch): ?>
            <div class="dataTables_filter pull-right col-sm-3" id="dataTable_filter">
                <label class="pull-right">Search: <input type="text" aria-controls="dataTable" class="quick-search form-control" value="<?php echo $this->quickSearch ?>">
                </label>
            </div>
        <?php endif; ?>
    </div>