<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="images/favicon.ico" type="image/ico" />

	<?= $this->headTitle('Gentelella Alela! |')->setSeparator(' - ')->setAutoEscape(false) ?>

	<?= $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

    <!-- Le styles -->
	<?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'])
		->prependStylesheet($this->basePath('css/style.css'))
		->prependStylesheet($this->basePath('gentella-admin/css/custom.min.css'))
    	->prependStylesheet($this->basePath('gentella-admin/nprogress/nprogress.css'))
		->prependStylesheet($this->basePath('gentella-admin/font-awesome/css/font-awesome.min.css'))
		->prependStylesheet($this->basePath('gentella-admin/bootstrap/dist/css/bootstrap.min.css'))
	?>
    <!-- Scripts -->
	<?= $this->headScript()
		->prependFile($this->basePath('js/app.js'))
		->prependFile($this->basePath('gentella-admin/jquery/dist/jquery.min.js'))
	?>

</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="login">
	<!-- Content Wrapper. Contains page content -->
    <div class="login_wrapper">
			<?= $this->content ?>
    </div>
			<!--------------------------
			  | Your Page Content Here |
	    -------------------------->
    <div class="body-processing">
        <div class="processing">

        </div>
    </div>
	<?= $this->inlineScript()
		->prependFile($this->basePath('gentella-admin/js/custom.min.js'))
		->prependFile($this->basePath('gentella-admin/nprogress/nprogress.js'))
		->prependFile($this->basePath('js/jquery.form.min.js'))
		->prependFile($this->basePath('gentella-admin/fastclick/lib/fastclick.js'))
		->prependFile($this->basePath('gentella-admin/bootstrap/dist/js/bootstrap.min.js'))
	?>
</body>
</html>