<p style="font-size: 1.3em">Caro(a) {user_name},</p>
<p>Este e-mail é para dar a você as boas vindas a nosso site!</p>
<p>Uma nova conta foi criada para que você possa ter mais comodidade e agilidade ao interagir conosco. Ao logar-se em sua conta você pode:</p>
<p>
	✓ Atualizar seus dados pessoais!<br>
	✓ Acompanhar o andamento dos seus pedidos!<br>
	✓ Realizar novos pedidos com mais agilidade!<br>
	✓ Ter acesso a ofertas exclusivas do site por e-mail!
</p>
<p>Confira abaixo os dados de acesso a sua conta:</p>
<p style="font-size: 1.1em">
	Login: {user_email}<br>
	Senha: {UserPassBook}<br>
</p>
<p><a title="Minha Conta" target="_blank" href="{base_url}/conta/login">Acessar Minha Conta!</a></p>
<p>Ao acessar nosso site você pode usar esses dados para identificar-se, e assim ter acesso ao melhor do nosso conteúdo...</p>
<p><b>Seja muito bem-vindo(a) {user_name}...</b></p>
<p><i>Atenciosamente, {site_name}!</i></p>