<?php
/**
 * Created By: Claudio  Campos
 * E-Mail: callcocam@gmail.com
 */

namespace Blog\Model;


use Core\Model\AbstractModel;
use Zend\InputFilter\InputFilter;

class PostsModel extends AbstractModel
{
	public function getInputFilter()
	{
		if (!$this->inputFilter):
			$this->inputFilter = new InputFilter();
		endif;
		return parent::getInputFilter(); // TODO: Change the autogenerated stub
	}
}