<!-- Content Header (Page header) -->
<?= $this->partial(sprintf("partial/%s/top-navigation", LAYOUT),[
	'a'=>"Admin",'b'=>$this->route,'c'=>$this->controller,'d'=>"Menu", "e"=>'editar']); ?>

<!-- Main content -->
<section class="content">
	<div class="row">
		<div class="col-md-3">

			<!-- Profile Image -->
			<div class="box box-primary">
				<div class="box-body box-profile">
				   <div id="uploadContainer">

                    </div>
					<?php $this->ZfForm()->upload(base64_decode($this->Route()->getId()));?>
					<h3 class="profile-username text-center"><?= $data->first_name ?> <?= $data->last_name ?></h3>

					<p class="text-muted text-center"><?= $data->access ?></p>

					<ul class="list-group list-group-unbordered">
						<li class="list-group-item">
							<b>E-Mail</b> <a class="pull-right"><?= $data->email ?></a>
						</li>
					</ul>

					</div>
				<!-- /.box-body -->
			</div>
			<!-- /.box -->

			<!-- About Me Box -->
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title">Sobre mim</h3>
				</div>
				<!-- /.box-header -->
				<div class="box-body">
					<strong><i class="fa fa-book margin-r-5"></i> Education</strong>

					<p class="text-muted">
						B.S. in Computer Science from the University of Tennessee at Knoxville
					</p>

					<hr>

					<strong><i class="fa fa-map-marker margin-r-5"></i> Location</strong>

					<p class="text-muted">Malibu, California</p>

					<hr>

					<strong><i class="fa fa-pencil margin-r-5"></i> Skills</strong>

					<p>
						<span class="label label-danger">UI Design</span>
						<span class="label label-success">Coding</span>
						<span class="label label-info">Javascript</span>
						<span class="label label-warning">PHP</span>
						<span class="label label-primary">Node.js</span>
					</p>

					<hr>

					<strong><i class="fa fa-file-text-o margin-r-5"></i> Notes</strong>

					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
				</div>
				<!-- /.box-body -->
			</div>
			<!-- /.box -->
		</div>
		<!-- /.col -->
		<div class="col-md-9">
			<div class="nav-tabs-custom">
				<ul class="nav nav-tabs">
					<li class="active"><a href="#settings" data-toggle="tab" aria-expanded="false">Settings</a></li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane active" id="settings">
						<div id="formContainer">

						</div>
						<?=$this->ZfForm()->form();?>
						</div>
					<!-- /.tab-pane -->
				</div>
				<!-- /.tab-content -->
			</div>
			<!-- /.nav-tabs-custom -->
		</div>
		<!-- /.col -->
	</div>
	<!-- /.row -->

</section>