<div class="search">
    <h3>PESQUISAR POR</h3>
    <form method="post" action="<?=$this->url("web-blog", ['action'=>'pesquisa'])?>">
        <input name="pesquisa" type="text" placeholder="Pesquisar">
        <input type="submit" value="">
    </form>
</div>
<?php
/* @var $container Zend\Navigation\Navigation */
$container = $this->container;
if ($container):?>
	<?php foreach ($container as $page): ?>
		<?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
		<?php $hasChildren = $page->hasPages() ?>
		<?php
		if ($hasChildren):	?>
                <div class="categories">
                    <h3><?=$this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?></h3>
					<?php foreach ($page->getPages() as $child): ?>
						<?php if ($child->get("separator") === true): ?>
                            <li class="divider"></li>
							<?php
							continue;
						endif;
						?>
                        <li class="<?=$page->isActive()? 'active':'' ?>"><a href="<?=$child->getHref();?>"><?=$this->escapeHtml($this->translate($child->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?></a></li>
					<?php endforeach ?>
                </div>
		<?php else: ?>
            <div class="categories">
                <h3><?=$this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?></h3>
            </div>
		<?php endif ?>
	<?php endforeach ?>
	<?php
endif;
?>