

   <!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
    </div>
</div>

<div class="container">
    <!-- Example row of columns -->
    <div class="row">

        <?php if($this->data):?>
            <?php foreach ($this->data as $row):?>
                <div class="col-md-4">
                    <h2><?=$row['name']?></h2>
                    <p><?=$row['preview']?> </p>
                    <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
                </div>
            <?php endforeach;?>
        <?php endif;?>


    </div>

      <hr>

      