<p style="font-size: 1.3em">Caro(a) <?=$this->sis?>,</p>
<p>Estou -<?=$this->name?>- entrando em contato para saber mais sobre!</p>

<p style="font-size: 1.1em">
	<?php echo $this->message?>
	<br>
</p>
<p>
	Nome: <?php echo $this->name?> <br>
	Email: <?php echo $this->email?><br>
	Phone: <?php echo $this->phone?><br>
</p>
<p><i>Contato vindo do site, <a href="<?php echo $this->url?>"><?php echo $this->sis?></a> !</i></p>
