<div class="zf-table-wrap  form-inline">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
					<?php if ($this->name): ?>
                        <h3 class="box-title">
							<?= $this->name ?>
                        </h3>
					<?php endif; ?>
                    <div class="box-tools">
						<?php if ($this->valuesOfState): ?>
                            <label class="pull-right">
                                <select  style="margin-left: 10px;" class="valuesState form-control input-sm">
									<?php foreach ($this->valuesOfState as $key => $item): ?>
										<?php $selected = ($key == $this->valuesState) ? 'selected' : ''; ?>
                                        <option value="<?= $key ?>" <?= $selected ?>><?= $item ?></option>
									<?php endforeach; ?>
                                </select>
                            </label>
						<?php endif; ?>
						<?php if ($this->showItemPerPage): ?>
                            <label class="pull-right">
                                <select  style="margin-left: 10px;" class="itemPerPage form-control input-sm">
									<?php foreach ($this->itemCountPerPageValues as $item): ?>
										<?php $selected = ($item == $this->itemCountPerPage) ? 'selected' : ''; ?>
                                        <option <?= $selected ?>><?= $item ?></option>
									<?php endforeach; ?>
                                </select>
                            </label>
						<?php endif; ?>
                        <div class="input-group input-group-sm" id="dataTable_filter" style="width: 150px;">
                            <input name="table_search" aria-controls="dataTable" class="quick-search form-control pull-right" placeholder="Search" type="text" value="<?= $quickSearch ?>">
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
				<?= $this->partial('box-controls', [
				        'route'=>$this->route,
				        'controller'=>$this->controller,
                        'pages' => $this->pages,
                         'valueButtonsActions'=>$this->valueButtonsActions,
                         'valuesState'=>$this->valuesState,
                ]); ?>
                <!-- /.box-header -->
                <div class="box-body table-responsive">
					<?=$this->table?>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2"><div class="dataTables_paginate paging_bootstrap pagination">
								<?php if ($this->showPagination): ?>
										<?php echo $this->paginator; ?>
								<?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box -->
        </div>
    </div>
	<?php echo $this->paramsWrap; ?>
</div>
<?=$this->partial('partial/messages');?>
<?=$this->ICheck();?>