<?php $companys = $this->companys();?>

<?php $this->placeholder('pagetitle')->captureStart();?>
<h1><?=$this->translate('CONTACT')?></h1>
<h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h2>
<?php $this->placeholder('pagetitle')->captureEnd() ?>



<div class="contact">
    <div class="container">
        <div class="contact-head">
            <h3>CONTATO</h3>
            <div id="formContainer">

            </div>
			<?php  $this->ZfForm()->form();?>
        </div>
        <div class="address">
            <h3>Our Locations</h3>
            <div class="col-md-12 locations">
                <ul>
                    <li><span></span></li>
                    <li>
                        <div class="address-info">
                            <h4><?=$companys['street']?>, <?=$companys['number']?>, <?=$companys['district']?></h4>
                            <p><?=$companys['city']?></p>
                            <p><?=$companys['zip']?>, <?=$companys['state']?>, <?=$companys['country']?>,</p>
                            <p>Telefone: <?=$companys['phone']?></p>
                            <p>Mail: <a href="mailto:<?=$companys['email']?>"><?=$companys['email']?></a></p>
                            <h5><a target="_blank" href="https://goo.gl/maps/KxJ6JCB7VDv">Visite no Google Maps >></a></h5>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<?=$this->partial('partial/seo',[
	'data'=>$companys
]);?>