<div class="content">
	<div class="container">
		<div class="content-grids">
			<div class="col-md-8 content-main">

                <?php if($this->data):?>
                    <?php foreach ($this->data as $data):?>
                <div class="content-grid">
					<div class="content-grid-head">
						<h3>POST OF THE DAY</h3>
						<h4><?=$this->dateFormat(new DateTime($data['created_at']), IntlDateFormatter::MEDIUM)?> ,Posted by: <a href="#"><?=$data['first_name']?> <?=$data['last_name']?></a></h4>
						<div class="clearfix"></div>
					</div>
					<div class="content-grid-info">
						<h3><a href="<?=$this->url('web-blog',[
								'action'=>'post',
								'slug'=>$data['alias']
							])?>"><?=$data['name']?></a></h3>
						<p><?=$data['preview']?></p>
						<img src="<?=$this->basePath($data['cover'])?>" alt=""/>
						<a class="bttn" href="<?=$this->url('web-blog',[
						        'action'=>'post',
                                'slug'=>$data['alias']
                        ])?>">MORE</a>
					</div>
				</div>
                <?php endforeach;?>
                <?php endif;?>

				<div class="pages">
					<ul>
						<li class="active"><a href="#">1</a></li>
						<li><a href="#">2</a></li>
						<li><a href="#">3</a></li>
						<li><a href="#">4</a></li>
						<li><a href="#">5</a></li>
						<li><a href="#">6</a></li>
						<li><a href="#">Previous</a></li>
						<li><a href="#">Next</a></li>
					</ul>
				</div>
			</div>

			<div class="col-md-4 content-main-right">
				<div class="search">
					<h3>SEARCH HERE</h3>
					<form>
						<input type="text" value="" onfocus="this.value=''" onblur="this.value=''">
						<input type="submit" value="">
					</form>
				</div>
				<div class="categories">
					<h3>CATEGORIES</h3>
					<li class="active"><a href="#">Donec quis dui at dolor tempor</a></li>
					<li><a href="#">Vestibulum commodo felis quis tort</a></li>
					<li><a href="#">Fusce pellentesque suscipit</a></li>
				</div>
				<div class="archives">
					<h3>ARCHIVES</h3>
					<li class="active"><a href="#">July 2014</a></li>
					<li><a href="#">June 2014</a></li>
					<li><a href="#">May 2014</a></li>
				</div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</div>
<!--fotter-->