<?php $companys = $this->companys();?>
<?php $this->placeholder('pagetitle')->captureStart();?>
<h1>Bem Vindo Ao Nosso Blog!</h1>
<h2>Veja as novidades do nosso projeto aqui!</h2>
<?php $this->placeholder('pagetitle')->captureEnd() ?>
<div class="content">
    <div class="container">
        <div class="content-grids">
            <div class="col-md-8 content-main">
				<?php if($this->data):?>
					<?php foreach ($this->data as $data):?>
                        <div class="content-grid">
                            <div class="content-grid-head">
                                <h3>POST OF THE DAY</h3>
                                <h4><?=$this->dateFormat(new DateTime($data['created_at']), IntlDateFormatter::MEDIUM)?> ,Posted by: <a href="#"><?=$data['first_name']?> <?=$data['last_name']?></a></h4>
                                <div class="clearfix"></div>
                            </div>
                            <div class="content-grid-info">
                                <h3><a href="<?=$this->url('web-blog',[
										'action'=>'post',
										'slug'=>$data['alias']
									])?>"><?=$data['name']?></a></h3>
                                <p><?=$data['preview']?></p>
                                <img src="<?=$this->basePath($data['cover'])?>" alt=""/>
                                <a class="bttn" href="<?=$this->url('web-blog',[
									'action'=>'post',
									'slug'=>$data['alias']
								])?>">VER MAIS</a>
                            </div>
                        </div>
					<?php endforeach;?>
				<?php endif;?>
            </div>
            <div class="col-md-4 content-main-right">
               <?=$this->navigation(\Webblog\Service\Categorie::class)->menu()
					->setPartial('partial/categorie');?>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<?=$this->partial('partial/seo',[
	'data'=>$companys
]);?>
<!--fotter-->