<div class="content">
	<?php $companys = $this->companys();?>
	<div class="container">
		<div class="content-grids">
			<div class="col-md-8 content-main">
				<?php if($this->data):?>
                    <?php
					$companys['title'] = $this->data['name'];
					$companys['cover'] = $this->data['cover'];
					$companys['preview'] = $this->data['preview'];
					 ?>

                    <?php $this->placeholder('pagetitle')->captureStart();?>
                    <h1><?= $this->data['name'] ?></h1>
                    <h2><?= $this->data['preview'] ?></h2>
					<?php $this->placeholder('pagetitle')->captureEnd() ?>


                   <div class="content-grid">
					<div class="content-grid-head">
						<h3><?=$this->translate('POST OF THE DAY')?></h3>
						<h4><?=$this->dateFormat(new DateTime($this->data['created_at']), IntlDateFormatter::MEDIUM)?>, <?=$this->translate('Posted by')?>: <a href="#"><?=$this->data['first_name']?> <?=$this->data['last_name']?></a></h4>
						<div class="clearfix"></div>
					</div>
					<div class="content-grid-single">
						<h3><?=$this->data['name']?></h3>
						<span><?=$this->data['preview']?></span>
                        <?php if(empty($this->data['video'])):?>
						<img class="single-pic" src="<?=$this->basePath($this->data['cover'])?>" alt=""/>
						<?php else:?>
                            <iframe id="mediaview" style="width: 100%;height: 450px;" src="https://www.youtube.com/embed/<?=$this->data['video']?>?rel=0&amp;showinfo=0&autoplay=0&origin=<?=$this->url("home",[],['force_canonical' => true]);?>" frameborder="0" allowfullscreen></iframe>
                        <?php endif;?>
                        <p><?=$this->data['description']?></p>
						<div class="comments">
							<h3>Comentarios</h3>
                            <div class="fb-comments" data-href="https://www.zenddesk.sigasmart.com.br/blog/post/<?=$this->data['alias']?>" data-numposts="5"></div>
                          </div>
					</div>

				</div>
				<?php endif;?>
			</div>
			<div class="col-md-4 content-main-right">
					<?=$this->navigation(\Webblog\Service\Categorie::class)->menu()
						->setPartial('partial/categorie');?>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</div>

<?php $this->partial('partial/seo',[
	'data'=>$companys
]);?>

<div id="fb-root"></div>
<script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.11&appId=657705874367292';
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>