<div class="content">
	<div class="container">
		<div class="content-grids">
			<div class="col-md-8 content-main">
				<?php if($this->data):?>
				<div class="content-grid">
					<div class="content-grid-head">
						<h3>POST OF THE DAY</h3>
						<h4><?=date_pt($data['created_at'],"D, M Y")?>,Posted by: <a href="#"><?=$data['first_name']?> <?=$data['last_name']?></a></h4>
						<div class="clearfix"></div>
					</div>
					<div class="content-grid-single">
						<h3><?=$this->data['name']?></h3>
						<span><?=$this->data['preview']?></span>
						<img class="single-pic" src="<?=$this->basePath($this->data['cover'])?>" alt=""/>
						<p><?=$this->data['description']?></p>

						<div class="content-form">
							<h3>Leave a comment</h3>
							<form>
								<textarea placeholder="Message"></textarea>
								<input type="submit" value="SEND"/>
							</form>
						</div>
						<div class="comments">
							<h3>Comment</h3>
							<div class="comment-grid">
								<img src="images/pic.png" alt=""/>
								<div class="comment-info">
									<h4>MARK JOHNSON</h4>
									<p>Vivamus congue turpis in laoreet sem nec ultrices. Fusce blandit nunc vehicula massa vehicula tincidunt. Nam venenatis cursus urna sed gravida. Ut tincidunt elit ut quam malesuada consequat. Sed semper.</p>
									<h5>On April 14, 2014, 18:01</h5>
									<a href="#">Reply</a>
								</div>
								<div class="clearfix"></div>
							</div>

							<div class="comment-grid">
								<img src="images/pic.png" alt=""/>
								<div class="comment-info">
									<h4>MARK JOHNSON</h4>
									<p>Vivamus congue turpis in laoreet sem nec ultrices. Fusce blandit nunc vehicula massa vehicula tincidunt. Nam venenatis cursus urna sed gravida. Ut tincidunt elit ut quam malesuada consequat. Sed semper.</p>
									<h5>On April 14, 2014, 18:01</h5>
									<a href="#">Reply</a>
								</div>
								<div class="clearfix"></div>
							</div>
						</div>
					</div>

				</div>
				<?php endif;?>
			</div>

			<div class="col-md-4 content-main-right">
				<div class="search">
					<h3>SEARCH HERE</h3>
					<form>
						<input type="text" value="" onfocus="this.value=''" onblur="this.value=''">
						<input type="submit" value="">
					</form>
				</div>
				<div class="categories">
					<h3>CATEGORIES</h3>
					<li class="active"><a href="#">Donec quis dui at dolor tempor</a></li>
					<li><a href="#">Vestibulum commodo felis quis tort</a></li>
					<li><a href="#">Fusce pellentesque suscipit</a></li>
				</div>
				<div class="archives">
					<h3>ARCHIVES</h3>
					<li class="active"><a href="#">July 2014</a></li>
					<li><a href="#">June 2014</a></li>
					<li><a href="#">May 2014</a></li>
				</div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</div>