<div class="content">
	<div class="row">
		<?php
		$i=1;
		foreach($this->rows as $row):
		?>
		<div class="col-md-55">
			<div class="thumbnail">
				<div class="image view view-first">
					<?=$row['cover'];?>
					<div class="mask">
						<p><?=$row['title']?></p>
						<div class="tools tools-bottom">
							<a href="#"><i class="fa fa-link"></i></a>
							<a href="#"><i class="fa fa-pencil"></i></a>
							<a href="#"><i class="fa fa-times"></i></a>
						</div>
					</div>
				</div>
				<div class="caption">
					<p><?=$row['uf']?>, <?=$row['cep']?>, <?=$row['ibge']?></p>
				</div>
			</div>
		</div>
		<?php
		if($i>=5):?>
	</div>
	<div class="row">
		<?php
		$i=0;
		endif;
		$i++;
		endforeach;?>
	</div>
</div>