<?=$this->partial('partial/form-error',['form'=>$this->form]);?>
<?=$this->form()->openTag($this->form->setAttribute('action',$this->url($this->route, [
	'controller'=>$this->controller,
	'action'=>'editar-form'
]))->setAttribute('name','AjaxForm'));?>
<?=$this->formHidden($this->form->get('id'));?>

<?=$this->partial(sprintf('partial/%s/form/input-inline', LAYOUT),[
	'field'=>$this->form->get('parent')
]);?>

<?=$this->partial(sprintf('partial/%s/form/input-inline', LAYOUT),[
	'field'=>$this->form->get('name')
]);?>

<?=$this->partial(sprintf('partial/%s/form/input-inline', LAYOUT),[
	'field'=>$this->form->get('alias')
]);?>
<?=$this->partial(sprintf('partial/%s/form/input-inline', LAYOUT),[
	'field'=>$this->form->get('resource')
]);?>
<?=$this->partial(sprintf('partial/%s/form/input-inline', LAYOUT),[
	'field'=>$this->form->get('role')
]);?>
<?=$this->partial(sprintf('partial/%s/form/input-inline', LAYOUT),[
	'field'=>$this->form->get('created_at')
]);?>

<?=$this->partial(sprintf('partial/%s/form/input-inline', LAYOUT),[
	'field'=>$this->form->get('updated_at')
]);?>
	<div class="row">
		<!-- /.col -->
		<div class="col-xs-6 col-xs-offset-3">
			<?=$this->formSubmit($this->form->get('submit')->setValue('Atualizar Privilégio'));?>
		</div>
		<div class="col-xs-3">
			<a href="<?=$this->url($this->route, [
				'controller'=>$this->controller
			])?>" class="btn btn-warning btn-block"><i class="fa fa-backward"></i> Voltar Para a Lista </a>
		</div>
		<!-- /.col -->
	</div>
<?=$this->form()->closeTag();?>
<?=$this->partial('partial/messages');?>