<?php
/**
 * Created By: Claudio  Campos
 * E-Mail: callcocam@gmail.com
 */

namespace Admin\Model;


use Core\Model\AbstractModel;
use Zend\InputFilter\InputFilter;

class EmpresaModel extends AbstractModel
{
	public function getInputFilter()
	{
		if (!$this->inputFilter):
			$this->inputFilter = new InputFilter();
			########################### social ####################
			$this->inputFilter->add([
				'name'=>'social',
				'required'=>true,
				'filters'=>$this->filters(),
				'validators'=>[
					$this->StringLength('Social'),
					$this->NotEmpty('Social'),//Manter somene se for campo obrigatorio
				]
			]);

			########################### fantasia ####################
			$this->inputFilter->add([
				'name'=>'fantasia',
				'required'=>true,
				'filters'=>$this->filters(),
				'validators'=>[
					$this->StringLength('Nome Fantasia'),
					$this->NotEmpty('Nome Fantasia'),//Manter somene se for campo obrigatorio
				]
			]);

			########################### phone ####################
			$this->inputFilter->add([
				'name'=>'phone',
				'required'=>true,
				'filters'=>$this->filters(),
				'validators'=>[
					$this->StringLength('Telefone'),
					$this->NotEmpty('Telefone'),//Manter somene se for campo obrigatorio
				]
			]);

			########################### email ####################
			$this->inputFilter->add([
				'name'=>'email',
				'required'=>true,
				'filters'=>$this->filters(),
				'validators'=>[
					$this->NoRecordExists("empresa"),
					$this->StringLength('E-Mail'),
					$this->NotEmpty('E-Mail'),//Manter somene se for campo obrigatorio
				]
			]);
			########################### cnpj ####################
			$this->inputFilter->add([
				'name'=>'cnpj',
				'required'=>true,
				'filters'=>$this->filters(),
				'validators'=>[
					$this->NoRecordExists("empresa",'cnpj','Cnpj'),
					$this->StringLength('Cnpj'),
					$this->NotEmpty('Cnpj'),//Manter somene se for campo obrigatorio
				]
			]);

			########################### street ####################
			$this->inputFilter->add([
				'name'=>'street',
				'required'=>true,
				'filters'=>$this->filters(),
				'validators'=>[
					$this->StringLength('Endereço'),
					$this->NotEmpty('Endereço'),//Manter somene se for campo obrigatorio
				]
			]);

			########################### district ####################
			$this->inputFilter->add([
				'name'=>'district',
				'required'=>true,
				'filters'=>$this->filters(),
				'validators'=>[
					$this->StringLength('Bairro'),
					$this->NotEmpty('Bairro'),//Manter somene se for campo obrigatorio
				]
			]);
			########################### city ####################
			$this->inputFilter->add([
				'name'=>'city',
				'required'=>true,
				'filters'=>$this->filters(),
				'validators'=>[
					$this->StringLength('Cidade'),
					$this->NotEmpty('Cidade'),//Manter somene se for campo obrigatorio
				]
			]);
			########################### state ####################
			$this->inputFilter->add([
				'name'=>'state',
				'required'=>true,
				'filters'=>$this->filters(),
				'validators'=>[
					$this->StringLength('Estado'),
					$this->NotEmpty('Estado'),//Manter somene se for campo obrigatorio
				]
			]);

			########################### zip ####################
			$this->inputFilter->add([
				'name'=>'zip',
				'required'=>true,
				'filters'=>$this->filters(),
				'validators'=>[
					$this->StringLength('Cep'),
					$this->NotEmpty('Cep'),//Manter somene se for campo obrigatorio
				]
			]);

		endif;
		return parent::getInputFilter(); // TODO: Change the autogenerated stub
	}
}