<?php
/**
 * Created By: Claudio  Campos
 * E-Mail: callcocam@gmail.com
 */

namespace Admin\Model;


use Core\Model\AbstractModel;
use Zend\InputFilter\InputFilter;

class MenuModel extends AbstractModel
{
	public function getInputFilter()
	{
		if (!$this->inputFilter):
			$this->inputFilter = new InputFilter();
		        ########################### parent ####################
				$this->inputFilter->add([
						'name'=>'parent',
						'required'=>false,
						'filters'=>$this->filters(),
						'validators'=>[
							$this->StringLength('Menu Principal'),
							
						]
					]);
			$this->inputFilter->add([
				'name'=>'ordem',
				'required'=>false,
				'filters'=>$this->filters(),
				'validators'=>[
					$this->StringLength('ordem'),

				]
			]);
		endif;
		return parent::getInputFilter(); // TODO: Change the autogenerated stub
	}
}