<?php
/**
 * Created By: Claudio  Campos
 * E-Mail: callcocam@gmail.com
 */

namespace Admin\Model;


use Core\Model\AbstractModel;
use Zend\InputFilter\InputFilter;

class UserModel extends AbstractModel
{
	public function getInputFilter()
	{
		if (!$this->inputFilter):
			$this->inputFilter = new InputFilter();

			########################### first_name ####################
			$this->inputFilter->add([
				'name'=>'first_name',
				'required'=>true,
				'filters'=>$this->filters(),
				'validators'=>[
					$this->StringLength('Nome'),
					$this->NotEmpty('Nome'),//Manter somene se for campo obrigatorio
				]
			]);

			########################### last_name ####################
			$this->inputFilter->add([
				'name'=>'last_name',
				'required'=>true,
				'filters'=>$this->filters(),
				'validators'=>[
					$this->StringLength('Sobre Nome'),
					$this->NotEmpty('Sobre Nome'),//Manter somene se for campo obrigatorio
				]
			]);

			########################### email ####################
			$this->inputFilter->add([
				'name'=>'email',
				'required'=>true,
				'filters'=>$this->filters(),
				'validators'=>[
					$this->NoRecordExists(),
					$this->StringLength('E-Mail'),
					$this->NotEmpty('E-Mail'),//Manter somene se for campo obrigatorio
				]
			]);

			########################### access ####################
			$this->inputFilter->add([
				'name'=>'access',
				'required'=>true,
				'filters'=>$this->filters(),
				'validators'=>[
					$this->StringLength('Acesso'),
					$this->NotEmpty('Acesso'),//Manter somene se for campo obrigatorio
				]
			]);
		endif;
		return parent::getInputFilter(); // TODO: Change the autogenerated stub
	}
}