<?php
/**
 * Created by PhpStorm.
 * User: caltj
 * Date: 18/12/2017
 * Time: 07:57
 */

namespace Auth\Model;


use Core\Model\AbstractModel;
use Zend\Filter\StringTrim;
use Zend\Filter\StripTags;
use Zend\InputFilter\InputFilter;
use Zend\Validator\NotEmpty;
use Zend\Validator\StringLength;

class LoginModel extends AbstractModel
{
	public function getInputFilter()
	{
		if (!$this->inputFilter):
         $this->inputFilter = new InputFilter();
            $this->inputFilter->add([
                    'name'=>'first_name',
					'required'=>true,
				    'filters'=>[
				    	[
				    		'name'=>StringTrim::class,
						],
						[
							'name'=>StripTags::class
						]
					],
				'validators'=>[
					[
						'name' => StringLength::class,
						'options' => [
							'max' => 255,
							'min' => 1,
							'messages' => [
								StringLength::TOO_SHORT => "Campo [Nome] Muito Curto",
								StringLength::TOO_LONG => "Campo [Nome] Muito Longo",
							],
						],
					],
					[
						'name' => NotEmpty::class,
						'options' => [
							'messages' => [NotEmpty::IS_EMPTY => "Campo [Nome] Obrigatorio"],
						],
					],
				]
			]);
		endif;
		return parent::getInputFilter(); // TODO: Change the autogenerated stub
	}


}